# Generated by Django 4.2.11 on 2024-04-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clients",
            name="client_phon_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
