# Generated by Django 4.2.11 on 2024-04-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_clients_client_phon_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="clients",
            name="client_course_tarif",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="groups",
            name="group_tarif",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
